spring:
  application:
    name: mcp
  main:
    web-application-type: none
  
  ai:
    # Set credentials for your Anthropic API account 
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}

    # Connect to the MCP Weather Server using streamable-http client transport
    mcp:
      client:
        streamable-http:
          connections:
            my-weather-server:
              url: http://localhost:8080        
        stdio:
          connections:
            brave-search:
              command: npx
              args:
                - "-y"
                - "@modelcontextprotocol/server-brave-search"        

# Debug configuration (commented out)
# debug: true
